apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-microblog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Areeba-Urooj/GitOps-3_Tier-CD.git
    targetRevision: main
    path: k8s-prod    # This is the KEY change - pointing to your app folder!
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

