---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: urooj275/microblog-api:9b0cacf1b69476abb75387e5c92c91d94f46b10a # Placeholder for the CI/CD pipeline to update
          ports:
            - containerPort: 8080 # Assuming your Go app listens on port 8080
          env:
            - name: DB_HOST
              value: postgres # The name of your PostgreSQL service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DB_PORT
              value: "5432" # The standard PostgreSQL port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: prod
spec:
  selector:
    app: backend
  ports:
    - port: 8080 # The port the service exposes
      targetPort: 8080 # The port on the container
  type: LoadBalancer # Changed to LoadBalancer for external access without Ingress
